# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3fbbc5542724367e0ebccc0fff794cca666dbd5b78f3170fb77bd1a136867d2ba09cec03599d0fca38068a2a33a83381b1d3b0a503e2c6e25de968e96056d9ca

test:
  secret_key_base: 7ee91e0435024a5177c6e26007590167b0ab4ec365a60c4c8ce2be26a582d2603c28aad4076afd19ecfac5416a549b918eefc545e39732678d373c47a94d7287

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
